### ISSUE TITLE
'ember-cli-bing-map' is not a properly formatted package

### ISSUE THREAD

**Issue by rvan1** [cometaworks/ember-cli-bing-map#3]
I tried to install this package with "ember install:addon ember-cli-bing-map", but got a "specified command install:addon is invalid" error. So I tried "ember install ember-cli-bing-map", but got a "package 'ember-cli-bing-map' is not a properly formatted package" error. With the old "bing-maps-element" package, it works but I get a "Microsoft is not defined" error so thought this CLI-oriented version might integrate better, but it doesn't.

**Comment by FutoRicky** [comment]
We are also getting the "...is not a properly formatted package" error but it is installing successfully. About the "Microsoft is not defined" message, make sure you add the map reference control in your index.html file as said in the readme. We do need to update it since ember-cli now installs addons using only ember install <addon>. We are currently working on that. Please let me know if adding the map control reference works for you. 

In the index.html add: 
`<script charset="UTF-8" type="text/javascript"src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"></script>`

**Comment by rvan1** [comment]
Oh I didn't realize it was installing even though there was the package error. I'm using an older ember bing map component which was always giving me the jshint Microsoft error, but found I just needed to add 'Microsoft' to jshintrc predefs. Yes the map (polymer component) works works via the script src added to index.html, or when I save the 'mapcontrol' script and import it via the brocfile.
